#!/usr/bin/env bash


#Build GoHub and move it to /usr/sbin
go build
cp ./gohub /usr/sbin/gohub


#Set up /etc/gohub and move configuration there
mkdir /etc/gohub
cp -r ./scripts /etc/gohub/scripts
cp -r ./config.json /etc/gohub/config.json


#Install Upstart script
cp ./upstart/gohub.conf /etc/init/gohub.conf